package com.example.util;

public enum Location {
    ZACHODNIO_POMORSKIE,
    POMORSKIE,
    WARMINSKO_MAZURSKIE,
    PODLASKIE,
    MAZOWIECKIE,
    KUJAWSKO_POMORSKIE,
    WIELKOPOLSKIE,
    LUBUSKIE,
    DOLNOSLASKIE,
    OPOLSKIE,
    LODZKIE,
    SWIETOKRZYSKIE,
    LUBELSKIE,
    PODKARPADZKIE,
    MALOPOLSKIE,
    SLASKIE,
    LAND
}
